apiVersion: v1
kind: Service
metadata:
  name: freeswitch
  labels:
    env: prod
    app: octopus
    component: freeswitch
spec:
  ports:
    - port: 5090
      targetPort: 5090
      protocol: UDP
      name: sip-internal
    - port: 5092
      targetPort: 5092
      protocol: UDP
      name: sip-external
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: webapi
      nodePort: 32001
    - port: 8021
      targetPort: 8021
      protocol: TCP
      name: event-socket
  type: NodePort
  selector:
    env: prod
    app: octopus
    component: freeswitch
