allowHostDirVolumePlugin: true
allowHostIPC: true
allowHostNetwork: true
allowHostPID: false
allowHostPorts: true
allowPrivilegedContainer: false
allowedCapabilities:
- IPC_LOCK
- NET_ADMIN
- NET_RAW
- NET_BROADCAST
- SYS_NICE
- SYS_RESOURCE
kind: SecurityContextConstraints
apiVersion: v1
metadata:
  name: scc-freeswitch
allowPrivilegedContainer: false
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: MustRunAs
fsGroup:
  type: RunAsAny
supplementalGroups:
  type: RunAsAny
users:
- system:serviceaccount:linkdesk-staging:freeswitch
volumes:
- configMap
- downwardAPI
- emptyDir
- persistentVolumeClaim
- secret
